# -------- General config --------
.DEFAULT_GOAL := all

PROJECT  := oled_demo
SRC_DIR  := src
INC_DIR  := include
BIN_DIR  := build/bin
OBJ_DIR  := build/obj

# All C sources in src/
SRCS := $(wildcard $(SRC_DIR)/*.c)
# Map each src to an object under OBJ_DIR with same basename
OBJS := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(SRCS))

CC      := gcc
CFLAGS  := -std=c11 -Wall -Wextra -O2 -I$(INC_DIR) -MMD -MP
LDLIBS  := -lwiringPi

# -------- Build rules --------
all: $(BIN_DIR)/$(PROJECT)

$(BIN_DIR)/$(PROJECT): $(OBJS) | $(BIN_DIR)
	$(CC) $(OBJS) $(LDLIBS) -o $@

# Compile each .c to .o (create obj subdir if needed)
$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c | $(OBJ_DIR)
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Ensure bin/ and obj/ exist
$(BIN_DIR) $(OBJ_DIR):
	mkdir -p $@

# -------- Convenience targets --------
.PHONY: run clean print
run: all
	@echo "Running $(BIN_DIR)/$(PROJECT) with sudo (I2C)…"
	sudo $(BIN_DIR)/$(PROJECT)

clean:
	rm -rf build

# Auto-include dependency files generated by -MMD
-include $(OBJS:.o=.d)